
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

      
spring:
  profiles:
    active:
      - dev
      
      
---
      
server:
  port: 8088           
      
spring:
  config:
    activate:
      on-profile:
        - dev


  datasource:
    mysql:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:log4jdbc:mysql://db.rigel.kr:3306/bilab?&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://db.rigel.kr:3306/bilab?&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: bilab
      password: bilab1234
    oracle:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      jdbc-url: jdbc:oracle:thin:@localhost:1521/xe

      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
      username: test
      password: 1234
#    hikari:
#      jdbc-url: 


  output:
    ansi:
      enabled: always



---

server:
  port: 8081
spring:
  config:
    activate:
      on-profile: prod     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hk-mysql:3306/cos?serverTimezone=Asia/Seoul
    username: root
    password: bitc5600

  jpa:
    hibernate:
      ddl-auto: update # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
